### ISSUE TITLE
Figure out how to access the MySQL DB on the server & document it on the wiki

### ISSUE THREAD

**Issue by AndreasGP** [olunet/SuperCap#1]

**Comment by AndreasGP** [comment]
This might be of help https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu-14-04

Although since we were provided a MySQL password, one would assume MySQL is already installed.

**Comment by AndreasGP** [comment]
A bit more information: I'm pretty sure it's installed and we have to use phpmyadmin to access it.

**Comment by githubERIK** [comment]
http://46.101.162.197/phpmyadmin
