### ISSUE TITLE
Write down initial functional requirements

### ISSUE THREAD

**Issue by AndreasGP** [olunet/SuperCap#4]

**Comment by githubERIK** [comment]
Commit [0aa9471] (https://github.com/olunet/SuperCap/wiki/_Functional-requirements/0aa94718761d892224ff6e796db93f2c2d6d7069)

**Comment by githubERIK** [comment]
Work includes: understand why the system will be built, and for whom it is useful, writing requirements to wiki.

Estimated: 2 man-hours
