### ISSUE TITLE
Create initial wiki structure for Collaboration Infrastructure - VCS page.

### ISSUE THREAD

**Issue by AndreasGP** [olunet/SuperCap#6]

**Comment by githubERIK** [comment]
Commit [68a0e76] (https://github.com/olunet/SuperCap/wiki/_Collaboration-Infrastructure---VCS/68a0e76731f275456bb51d616155f8fad7a9cd2c)

**Comment by githubERIK** [comment]
Work includes: creating information about VCS. 

Estimated: 0.1 man-hours
